server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway   #注册eureka的服务名

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com     #注册eureka服务实例id
    prefer-ip-address: true


zuul:
  #ignored-services: microservicecloud-dept  #隐藏真实服务名称
  prefix: /atguigu                           #统一公共前缀
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**                   #真实服务名称的路由映射

info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@

